project:
  type: website
  output-dir: _site

website:
  title: "NBA Scoring Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: scores.qmd
        text: Scores
      - href: history.qmd
        text: History
      - href: about.qmd
        text: About

format:
  html:
    theme: default
